<a href="https://colab.research.google.com/github/francistshimbombontata/apprentissage_machine_learning/blob/main/Bases_Python_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
LISTE = [1, 3.0, "Hello", print]
print(type(LISTE))

<class 'list'>


# Iterable

In [ ]:
iterator = iter(LISTE)
iterator

In [ ]:
next(iterator)

In [ ]:
for nombre in [1,2,3]:
  carre = nombre**2
  print(carre)

# Les 4 fonctions de Liste importantes

In [ ]:
# 1. La fonction "range()"
# La fonction "range" ne prend pas trop d'espace en mémoire par rapport aux objets LIST proprement dits
ma_range = range(10)

for i in ma_range:
  a=i
  print(a)
  #
ma_range_2 = range(10, 30)
for i in ma_range_2:
  print(i)
  #
ma_range_3 = range(10, 30, 10)
for i in ma_range_3:
  print(i)

In [ ]:
# 2. enumerate() : permet d'avoir l'index en même temps que la valeur
my_enumerate = enumerate(["A", "B", "C"])

for objet in my_enumerate:
  print(objet)
  #
# On peut parcourir aussi un objet "enumerate" comme suit :
for index, valeur in enumerate(["A", "B", "C"]):
  print(index, valeur)

In [ ]:
# 3. 'reversed()' : qui nous permet d'inverser l'ordre d'une collection
reversed_liste = reversed([1, 2, 3])
for i in reversed_liste:
  print(i)

In [ ]:
# 4. "zip()" : Mettre ensemble plusieurs iterables. La fonction va faire en
# réalité un "mappage"
plat = ["Poisson", "Salade", "Pizza", "Hamburger"]
prix = [18, 13, 24]

for plat, prix in zip(plat, prix):
  print(plat, prix)
#

Poisson 18
Salade 13
Pizza 24


# List Slicing

In [ ]:
import string
#
alphabet = string.ascii_lowercase
LISTE = list("abcdefghijklmnopqrstuvwxyz")
print(LISTE)

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']


In [ ]:
LISTE[-1]

In [ ]:
LISTE[:10]

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [ ]:
LISTE = list("ABCD")

In [ ]:
LISTE[1:3]

['B', 'C']

In [ ]:
LISTE[:-1]

['A', 'B', 'C']

# LIST COMPREHENSIONS

In [ ]:
ma_liste = [x**2 for x in range(10)]
ma_liste

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [ ]:
mon_set = {i**3 for i in range(10) if i%2==0}
mon_set

{0, 8, 64, 216, 512}

In [ ]:
mon_dico = {i:i**2 for i in range(10)}
mon_dico

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81}

# Multi-Level Indexing

In [ ]:
# Matrice = Liste à deux dimensions
matrix = [[0, 1, 2],
          [2, 3, 4]]

In [ ]:
matrix[0]

[0, 1, 2]

In [ ]:
# Tenseur = Liste à dimensions N >= 3. Avec Cube = Liste à 3 dimensions.
cube = [[[0, 1, 2], [2, 3, 4]],
        [[6, 8, 2], [5, 9, 4]]]
cube

[[[0, 1, 2], [2, 3, 4]], [[6, 8, 2], [5, 9, 4]]]

In [ ]:
cube[1][0][1]

8

In [ ]:
c=3
tenseur = [[['Z']*c for _ in range(c)] for _ in range(c)]
tenseur

[[['Z', 'Z', 'Z'], ['Z', 'Z', 'Z'], ['Z', 'Z', 'Z']],
 [['Z', 'Z', 'Z'], ['Z', 'Z', 'Z'], ['Z', 'Z', 'Z']],
 [['Z', 'Z', 'Z'], ['Z', 'Z', 'Z'], ['Z', 'Z', 'Z']]]

In [ ]:
tenseur[0][0][0] = 'A'
tenseur[1][1][0] = 'A'
tenseur[2][2][0] = 'A'
tenseur

[[['A', 'Z', 'Z'], ['Z', 'Z', 'Z'], ['Z', 'Z', 'Z']],
 [['Z', 'Z', 'Z'], ['A', 'Z', 'Z'], ['Z', 'Z', 'Z']],
 [['Z', 'Z', 'Z'], ['Z', 'Z', 'Z'], ['A', 'Z', 'Z']]]

In [ ]:
for i in range(c):
  tenseur[i][i][0] = 3
tenseur

[[[3, 'Z', 'Z'], ['Z', 'Z', 'Z'], ['Z', 'Z', 'Z']],
 [['Z', 'Z', 'Z'], [3, 'Z', 'Z'], ['Z', 'Z', 'Z']],
 [['Z', 'Z', 'Z'], ['Z', 'Z', 'Z'], [3, 'Z', 'Z']]]

In [ ]:
tenseur[0][0][-1] = 'A'
tenseur[1][1][-2] = 'A'
tenseur[2][2][-3] = 'A'
tenseur

[[['Z', 'Z', 'A'], ['Z', 'Z', 'Z'], ['Z', 'Z', 'Z']],
 [['Z', 'Z', 'Z'], ['Z', 'A', 'Z'], ['Z', 'Z', 'Z']],
 [['Z', 'Z', 'Z'], ['Z', 'Z', 'Z'], ['A', 'Z', 'Z']]]

In [ ]:
for i in range(c):
  tenseur[i][i][-(i+1)] = 'D'
tenseur

[[['Z', 'Z', 'D'], ['Z', 'Z', 'Z'], ['Z', 'Z', 'Z']],
 [['Z', 'Z', 'Z'], ['Z', 'D', 'Z'], ['Z', 'Z', 'Z']],
 [['Z', 'Z', 'Z'], ['Z', 'Z', 'Z'], ['D', 'Z', 'Z']]]

In [ ]:
compteur = 0
for i in range(c):
  for j in range(c):
    for k in range(c):
      tenseur[i][j][k] = compteur
      compteur += 1
tenseur

[[[0, 1, 2], [3, 4, 5], [6, 7, 8]],
 [[9, 10, 11], [12, 13, 14], [15, 16, 17]],
 [[18, 19, 20], [21, 22, 23], [24, 25, 26]]]

In [ ]:
tenseur = [[['Z']*c for _ in range(c)] for _ in range(c)]
compteur = 0
for i in range(c):
  for j in range(c):
    k=i-j
    tenseur[-(i+1)][j][k] = compteur
    compteur += 1
tenseur

[[['Z', 'Z', 6], ['Z', 7, 'Z'], [8, 'Z', 'Z']],
 [['Z', 3, 'Z'], [4, 'Z', 'Z'], ['Z', 'Z', 5]],
 [[0, 'Z', 'Z'], ['Z', 'Z', 1], ['Z', 2, 'Z']]]

# Les Vecteurs

In [ ]:
from random import randint
from random import seed

#Fonction pour fixer la valeur aléatoire


def creer_vecteur_aleatoire(dimension, a=0, b=10):
  return [randint(a, b) for _ in range(dimension)]

creer_vecteur_aleatoire(5)

[7, 3, 0, 9, 6]

In [ ]:
#Seed : permet de rendre fixent les valeurs aléatoires générées
seed(2025)
vecteur_1 = creer_vecteur_aleatoire(5)
vecteur_2 = creer_vecteur_aleatoire(5)
print(vecteur_1)
print(vecteur_2)


[8, 1, 10, 7, 2]
[8, 0, 5, 6, 9]


## Normes de Vecteurs

### Manhattan Norm (L1 Norm)
**‖v‖1=|v1|+|v2|+⋯+|v3|**

In [ ]:
# L1 Norm : En Regression Linéaire/Logistique, on parle de la "Régularisation L2"
#‖v‖1=|v1|+|v2|+⋯+|v3|
#
def manhattan_norm(vecteur):
  return sum([abs(x) for x in vecteur])

manhattan_norm(vecteur_1)

28

### Euclidean Norm (L2 Norm)
** ‖v‖2=√(v1^2+v2^2+⋯vn^2 )**

In [ ]:
# L2 Norm : En Regression Linéaire/Logistique, on parle de la "Régularisation L2"
# ‖v‖2=√(v1^2+v2^2+⋯vn^2 )
# square root
from math import sqrt
#
def euclidean_norm(vecteur):
  return sum([x**2 for x in vecteur])**0.5

def euclidean_norm_2(vecteur):
  return sqrt(sum([x**2 for x in vecteur]))
#
print(euclidean_norm(vecteur_1))
print(euclidean_norm_2(vecteur_1))
#

### Euclidean Distance between 2 vectors
**d(u,v)=∥u−v∥2** : The Euclidean norm of the difference of the two vectors.


In [ ]:
def euclidean_distance(vecteur_1, vecteur_2):
  return euclidean_norm([x-y for x, y in zip(vecteur_1, vecteur_2)])

def euclidean_distance_2(vecteur_1, vecteur_2):
  return euclidean_norm_2([x-y for x, y in zip(vecteur_1, vecteur_2)])

def euclidean_distance_3(vecteur_1, vecteur_2):
  return sqrt(sum([(x-y)**2 for x, y in zip(vecteur_1, vecteur_2)]))

print(euclidean_distance(vecteur_1, vecteur_2))
print(euclidean_distance_2(vecteur_1, vecteur_2))
print(euclidean_distance_3(vecteur_1, vecteur_2))

# Matrices

In [ ]:
from random import randint, seed
#
matrix1 = [[1, 2], [3, 4]]
matrix2 = [[5, 6], [7, 8]]
#

def creer_matrice_aleatoire(n_ligne, n_col, low=-5, high=5):
  return [[randint(low, high) for _ in range(n_col)] for _ in range(n_ligne)]

seed(2025)
matrix3 = creer_matrice_aleatoire(3, 4)
matrix3

[[3, -4, 5, 2], [-3, 3, -5, 0], [1, 4, -2, -4]]

## Différences entre "dimensions" et "ndim"

In [ ]:
# Pour une matrice. 'ndim vaut 2'. Exemple A[2][1]

## Shape.
La 'shape' n'est rien d'autre qu'un tuple qui reprend la taille d'une matrice, c'est-à-dire le nombre de ses lignes et le nombre de ses colonnes.

Exemple : Soit une matrice A de taill 3*4, alors la 'shape' s = (3,4).

In [ ]:
import numpy as np

matrix4 = np.array(matrix3)
matrix4.shape

def shape(matrix):
  return (len(matrix), len(matrix[0]))

matrix5 = creer_matrice_aleatoire(4, 3)
shape(matrix5)

(4, 3)

## Dot Product (Produit Scalaire)

In [ ]:
def dot_product(vect_1, vect_2):
  assert len(vect_1) == len(vect_2), f'Erreur : {len(vect_1)} != {len(vect_2)}'
  return sum([x*y for x, y in zip(vect_1, vect_2)])
#
dot_product(vecteur_1, vecteur_2)

174

## Matrix Multiplication : Mat. Mul

In [ ]:
def colonne(matrix, col):
  return [matrix[i][col] for i in range(len(matrix))]


#
def mat_mul(matrix_A, matrix_B):
  #
  shapeA = shape(matrix_A)
  shapeB = shape(matrix_B)
  # 0. Afficher les shapes de chaque matrice
  #print(f'Shape de A : {shapeA}')
  #print(f'Shape de B : {shapeB}')
  # 1. Nombre de colonnes de A == Nombre de lignes de B ==> (m, n) , (n,p)
  assert shapeA[1] == shapeB[0], f'Erreur : {shapeA[1]} != {shapeB[0]}'
  #
  # 2. Afficher la 'shape' du résultat
  shape_result = shapeA[0], shapeB[1]
  #print(f'Shape du résultat : {shape_result}')
  #
  # 3. Multiplication Matricielle
  matrix=[]

  for i in range(shape_result[0]): # Les lignes
    ligne = []
    for j in range(shape_result[1]): # Les colonnes
      ligne_A = matrix_A[i]
      colonne_B = [x[j] for x in matrix_B]
      resultat = dot_product(ligne_A, colonne_B)
      ligne.append(resultat)
    matrix.append(ligne)
  #
  return matrix

mat_mul(matrix1, matrix2)

A = creer_matrice_aleatoire(3, 4)
B = creer_matrice_aleatoire(4, 3)
#
mat_mul(matrix1, matrix2)

[[19, 22], [43, 50]]

## Matrice Identité ou Matrice Unité (Identity Matrix)

In [ ]:
def identity_matrix(n):
  return [[1 if i==j else 0 for j in range(n)] for i in range(n)]

def identity_matrix_2(n):
  matrix = []
  for i in range(n):
    ligne = []
    for j in range(n):
      nombre = 0
      if i==j:
        nombre = 1
        #
      ligne.append(nombre)
      #
    matrix.append(ligne)

  return matrix
    #
id_4 = identity_matrix(4)
id_5 = identity_matrix_2(5)



In [ ]:
matrixA = creer_matrice_aleatoire(6, 5, low=0, high=6)
matrixA

[[4, 6, 6, 3, 3],
 [5, 0, 6, 5, 4],
 [3, 5, 4, 0, 6],
 [2, 6, 4, 6, 1],
 [2, 1, 4, 4, 4],
 [2, 1, 6, 2, 2]]

In [ ]:
shape(matrixA), shape(id_5)

((6, 5), (5, 5))

In [ ]:
mat_mul(matrixA, id_5)

Shape de A : (6, 5)
Shape de B : (5, 5)
Shape du résultat : (6, 5)


[[4, 6, 6, 3, 3],
 [5, 0, 6, 5, 4],
 [3, 5, 4, 0, 6],
 [2, 6, 4, 6, 1],
 [2, 1, 4, 4, 4],
 [2, 1, 6, 2, 2]]

## Matrice Inverse (Inverse Matrix)

In [ ]:
mat3 = [[4,-2,3],
        [8,-3,5],
        [7,-2,4]]
inv3 = [[-2, 2, -1],
        [3, -5, 4],
        [5, -6, 4]]
#mat_mul(mat3, inv3)
mat_mul(inv3, mat3)

Shape de A : (3, 3)
Shape de B : (3, 3)
Shape du résultat : (3, 3)


[[1, 0, 0], [0, 1, 0], [0, 0, 1]]

In [ ]:
import numpy as np
inv3 = np.linalg.inv(mat3)

array([[-2.,  2., -1.],
       [ 3., -5.,  4.],
       [ 5., -6.,  4.]])

## Matrice Transposée (Transpose of Matrix)

In [ ]:
import numpy as np
np.transpose(mat3)

array([[ 4,  8,  7],
       [-2, -3, -2],
       [ 3,  5,  4]])

In [ ]:
def colonne(matrix, col):
  return [matrix[i][col] for i in range(len(matrix))]

def transpose(matrix):
  matrix_t = []
  for i in range(len(matrix[0])):
    matrix_t.append(colonne(matrix, i))
  return matrix_t
#
def transpose_2(matrix):
  return [colonne(matrix, i) for i in range(len(matrix[0]))]

mat3t = transpose(mat3)
print(mat3t)
mat3tt = transpose_2(mat3t)
print(mat3tt)
#

[[4, 8, 7], [-2, -3, -2], [3, 5, 4]]
[[4, -2, 3], [8, -3, 5], [7, -2, 4]]


# NumPy (Numerical Python)
Librairie Python qui rend possible le ML en Python.

Cette librairie suppporte deux autres librairies les plus utilisées : **Pandas** et **Scit-Learn**.

In [ ]:
import numpy as np

np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
a = np.random.randint(0, 10, size=(4, 3))
type(a)

numpy.ndarray

In [ ]:
a

array([[6, 6, 5],
       [7, 4, 4],
       [8, 1, 9],
       [8, 6, 9]])

In [ ]:
liste = [[6, 6, 5],
       [7, 4, 4],
       [8, 1, 9],
       [8, 6, 9]]
type(liste)

list

In [ ]:
liste_array = np.array(liste)
type(liste_array)


numpy.ndarray

In [ ]:
# Pour savoir la dimension
liste_array.ndim

2

In [ ]:
# Pour savoir la taille ou la shape
liste_array.shape

(4, 3)

In [ ]:
dimension = 200
A = np.random.randint(low = 0, high = 10, size=(dimension, dimension))
B= np.random.randint(low = 0, high = 10, size=(dimension, dimension))
A

array([[1, 6, 5, ..., 0, 3, 9],
       [3, 8, 2, ..., 3, 0, 2],
       [8, 9, 3, ..., 2, 7, 8],
       ...,
       [2, 5, 7, ..., 5, 7, 5],
       [7, 9, 9, ..., 2, 6, 9],
       [2, 0, 3, ..., 7, 4, 3]])

In [ ]:
B

array([[8, 2, 5, 2],
       [1, 1, 6, 1],
       [9, 6, 7, 3]])

In [ ]:
A.shape, B.shape

((200, 200), (200, 200))

In [ ]:
# Le nombre d'élément d'un Array
a.size

12

In [ ]:
# La Multiplication des Matrices avec NumPy
np.dot(A, B)

array([[4004, 4057, 4191, ..., 4522, 4381, 4035],
       [3556, 3623, 3290, ..., 3372, 3641, 3431],
       [3855, 3766, 3755, ..., 3973, 4232, 3767],
       ...,
       [3864, 4099, 3695, ..., 3911, 4111, 3695],
       [4007, 4135, 4048, ..., 3890, 4143, 3902],
       [3629, 3586, 3678, ..., 3787, 3623, 3609]])

In [ ]:
# La Transposée d'une matrice
AT = A.T # Ou encore
AT2 = np.transpose(A)
AT2

array([[5, 2, 2, 4],
       [2, 0, 0, 0],
       [5, 5, 8, 7]])

In [ ]:
C = np.ones(shape=(2, 5))
C

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# Transposée
C.T

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
from time import time
n_loop = 5
s_start = time()

for _ in range(n_loop):
  np.dot(A, B)
s_end = time()
t_numpy = (s_end - s_start)/n_loop
print(f'Temps effetué avec NUMPY {t_numpy}')

Temps effetué avec NUMPY 0.008363914489746094


In [ ]:
s_start = time()
for _ in range(n_loop):
  mat_mul(A, B)
s_end = time()
t_list = (s_end - s_start)/n_loop
print(f'Temps effetué avec LISTE {t_list}')

Temps effetué avec LISTE 3.6389434814453123


In [ ]:
t_list/t_numpy

435.0766003055802

In [ ]:
# Matrice Nulle
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# Matrice Identité
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Array Fundamentals

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
a[0]

np.int64(1)

In [ ]:
a[0] = 10
a

array([10,  2,  3,  4,  5,  6])

In [ ]:
a[:3]

array([10,  2,  3])

In [ ]:
b=a[3:]
b

array([4, 5, 6])

In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a.ndim

2

In [ ]:
a[0][1]

np.int64(2)

In [ ]:
a[0,1]

np.int64(2)

In [ ]:
# Type de données d'un Array
a.dtype

dtype('int64')

In [ ]:
# Créer un Array Vide avec 2 élements.
np.empty(3)

array([0. , 0.5, 1. ])

In [ ]:
# Créer un Array avec une plage d'élémennts
np.arange(5)

array([0, 1, 2, 3, 4])

In [ ]:
# Créer un Array avec une plage d'éléments avec un pas d'incrément
np.arange(2, 10, 2)

array([2, 4, 6, 8])

In [ ]:
# Array espacé linéairement avec un intervalle spécifié
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
# On peut spécifié le type des éléments d'un Array
np.ones(2, dtype=np.int64)

array([1, 1])

In [ ]:
# Reshape an Array
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [ ]:
a.size

6

In [ ]:
a.shape
b= a.reshape(2, 3)
print(b)

[[0 1 2]
 [3 4 5]]


In [ ]:
b.size

6

In [ ]:
np.reshape(a, (2, 3), order='C')

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
# Add a new axis to an Array : np.newaxis
# Convert a 1D to a row vector
row_vector = a[np.newaxis, :]
print(row_vector)
print(row_vector.shape)

[[0 1 2 3 4 5]]
(1, 6)


In [ ]:
# Convert a 1D to a column vector
col_vector = a[:, np.newaxis]
print(col_vector)
print(col_vector.shape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
(6, 1)


In [ ]:
# Inserting a new axis : np.expand_dims
a = np.array([1, 2, 3, 4, 5, 6])
a.shape
print(a)

[1 2 3 4 5 6]


In [ ]:
b = np.expand_dims(a, axis=1)
b.shape
print(b)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [ ]:
c = np.expand_dims(a, axis=0)
c.shape
print(c)

[[1 2 3 4 5 6]]


In [ ]:
# Indexing and Slicing
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a.shape)
print(a.ndim)
print(a)


(3, 4)
2
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
# All values less than 5
b = a[a<5]
b

array([1, 2, 3, 4])

In [ ]:
five_up = (a >= 5)
c = a[five_up]
print(c)

[ 5  6  7  8  9 10 11 12]


In [ ]:
d = a[(a>2) & (a< 11)]
print(d)

[ 3  4  5  6  7  8  9 10]


In [ ]:
# Pour tester si des valeurs existes à un point de coordonnées
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# On peut aussi la fonction 'nonzero'
b = np.nonzero(a < 5)
print(b)

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))


In [ ]:
#If you want to generate a list of coordinates where the elements exist, you # can zip the arrays, iterate over the list of coordinates, and print them.
coordinates_list = list(zip(b[0], b[1]))
for coord in coordinates_list:
    print(coord)

(np.int64(0), np.int64(0))
(np.int64(0), np.int64(1))
(np.int64(0), np.int64(2))
(np.int64(0), np.int64(3))


In [ ]:
#
a[b]

array([1, 2, 3, 4])

In [ ]:
len?

# Autres Ressources à consulter

## From my own research

0. https://www.coursera.org/specializations/mathematics-machine-learning (A voir si seulement nécessaire)

1. https://developers.google.com/machine-learning/intro-to-ml
2. https://developers.google.com/machine-learning/crash-course

3. https://www.coursera.org/professional-certificates/ibm-machine-learning,

4. https://www.coursera.org/specializations/deep-learning

5. https://www.coursera.org/specializations/packt-the-complete-quantum-computing-course-for-beginners
6. https://www.udemy.com/course/quantum-computers/?couponCode=2021PM20

## From Youtube
1. Python basics
2. Why Machines Learn: Anil Ananthaswamy
3. Andrew Ng ML specialization
4. Andrew Ng Deep learning specialization
5. CS25 Transformer Architecture
6. Andrej Karpathy YT all videos
7. Understanding Deep Learning Simon prince (for theory research top dense work)
8. Numpy/panda/matplotlib/pytorch/tensorflow/jax/sckit learn -> kaggle begginer projects
9.  Reading Research paper
10. show ur work & projects (linkedin/blog post/research paper submit)